version: "3"

services:
  rabbitmq_manager:
    container_name: test_rabbit_mq_management
    image: rabbitmq:3.9.7-management
    ports:
      - "35673:15672"
      - "35672:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=duarbdhks
      - RABBITMQ_DEFAULT_PASS=1234
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
